---
name: 'LaTeX Release Action'
description: 'Build LaTeX document and create GitHub Release'

inputs:
  files:
    description: 'Comma-separated list of LaTeX file names without .tex extension'
    required: true
  latex_options:
    description: 'Additional latexmk options'
    required: false
    default: '-interaction=nonstopmode'
  release_name:
    description: 'Custom release name (optional)'
    required: false
  cleanup:
    description: 'Clean up intermediate files after build'
    required: false
    default: 'true'
  parallel:
    description: 'Build files in parallel'
    required: false
    default: 'false'

outputs:
  pdf_files:
    description: 'Comma-separated list of generated PDF files'
  all_exist:
    description: 'Whether all expected PDF files were generated'
  processed_files:
    description: 'Comma-separated list of processed LaTeX files'

runs:
  using: 'docker'
  image: 'Dockerfile'
